---
- name: "Set journal log size limit" # to avoid hard drive filling up!
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#\s*SystemMaxUse='
    line: 'SystemMaxUse=100M'
  notify: Reload journald

- name: "Set file descriptors limit" # fairfood-issues#2733
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^#?DefaultLimitNOFILE'
    # double the default soft limit of 1024
    line: 'DefaultLimitNOFILE=2048:524288'
